### ISSUE TITLE
Producer shouldn't use multiprocessing

### ISSUE THREAD

**Issue by snaury** [mumrah/kafka-python#151]
Producer, when in async mode, uses multiprocessing. Unfortunately this breaks when application itself already uses multiprocessing, because nested processes are not allowed by multiprocessing. What's even more important is that this forces messages to be synchronously pickled and sent over the channel (multiprocessing.Queue) which should be unnecessary. I wanted to use Producer with batch_send=True, but due to these two reasons I effectively can't. Since async and batching is probably more about I/O wouldn't it be better to use threads for async Producers?

**Comment by vshlapakov** [comment]
I think we can close this issue.

**Comment by dpkp** [comment]
yes indeed -- thanks for all the help on this!
