### ISSUE TITLE
SimpleProducer(async=True) aborts then hangs

### ISSUE THREAD

**Issue by dennisjac** [mumrah/kafka-python#168]
Hi,
I'm getting my feet wet using Kafka and kafka-python by using a producer that pushed messages into a topic and a consumer that fetches them again.
Pushing 10.000 messages works fine and I can consume all messages ok. Once I set async=True however only a fraction of the messages get sent and the producer hangs on kafka.close().

topic = "test"
messages = 10000
kafka = KafkaClient("localhost:9092")
producer = SimpleProducer(kafka, async=True)
for i in range(messages):
    producer.send_messages(topic, "message %d" % (i))
kafka.close()

**Comment by dpkp** [comment]
closing -- async producer has gotten a facelift and should be much more reliable now (in master and as of 0.9.4 release)
