### ISSUE TITLE
Limit to kafka-python's Queue size.

### ISSUE THREAD

**Issue by JDShu** [mumrah/kafka-python#187]
I saw this is brought up in #137. When using kafka-python I've encountered cases where my application's memory usage increases uncontrollably because the internal kafka queue is filling up faster than the items can be shipped to Kafka. In my application code I hacked in some logic to check the producer.queue.queuesize before calling send_messages, but maybe it would be better and generally useful to others to set the Queue's maxsize in kafka-python itself and pass in a parameter to Producer?

**Comment by dpkp** [comment]
max queue size can now be configured via producer kwargs `async_queue_maxsize`
