### ISSUE TITLE
KeyedProducer doesn't actually send the key with the message

### ISSUE THREAD

**Issue by mjwillson** [mumrah/kafka-python#201]
This was kind of unexpected. It seems it's only using the key locally to decide the partition, but not actually serializing it with the message.

Is this intentional? If so it's probably worth documenting so people don't go crazy trying to track down bugs with the missing keys. It'd be nice to have an option at least to serialize the key when using a KeyedProducer.

**Comment by dpkp** [comment]
Fixed in #268 .  Additional fixes in #329
