### ISSUE TITLE
OffsetCommitRequest changes in 0.8.2?

### ISSUE THREAD

**Issue by jessemyers** [mumrah/kafka-python#247]
We were running into [KAFKA-1451](https://issues.apache.org/jira/browse/KAFKA-1451) repeatedly so we're trying out a build of 0.8.2 from trunk. We've noticed that OffsetCommitRequests no longer work because the protocol now expects a long long "timestamp" in the struct between the "offset" and "metadata" fields. We've tried changing the type and protocol definitions and can get Kafka to accept the request now -- previously, we would get a "FailedPayloadsError" because Kafka had an (understandable) underflow on read.

Unfortunately, we now get error code 15 (ConsumerCoordinatorNotAvailableCode).

The change in question was part of [KAFKA-1012](https://issues.apache.org/jira/browse/KAFKA-1012), but I can't (yet) figure out from that why the protocol changed or what this error means.

Has anyone else run into these problems?

**Comment by dpkp** [comment]
yes -- see [KAFKA-1841](https://issues.apache.org/jira/browse/KAFKA-1841) .  The api versioning issues w/ OffsetCommitRequests will be cleaned up before 0.8.2 is released.  Unfortunately, until then it is difficult for kafka-python to support trunk deployments.

and agree -- 1451 is a nasty one.
