### ISSUE TITLE
MultiProcessConsumer Cannot Set Options of SimpleConsumer Workers

### ISSUE THREAD

**Issue by rhema** [mumrah/kafka-python#248]
SimpleConsumer can be instantiated with options such as fetch_size_bytes, buffer_size,  and max_buffer_size. MultiProcessConsumer uses a pool SimpleConsumer workers, but instantiates them using their default configuration. This is a problem when log messages are large enough to need larger (fetch_size_bytes, buffer_size,  and max_buffer_size) than normal.

**Comment by dpkp** [comment]
fixed in #336
