### ISSUE TITLE
expanding cluster and reassigning partitions throws KeyError on produce

### ISSUE THREAD

**Issue by hzshlomi** [mumrah/kafka-python#264]
Hi,
I expanded a cluster of 3 kafka nodes to be 5 nodes and when I reassigned partitions to balance the load between all 5 I got KeyError and had to restart the producers. is there a way to avoid the restart? what needs to be done to have the producer self-update and continue producing after the reassignment?

**Comment by dpkp** [comment]
Couple thoughts:

This specific issue is in version `0.9.2` (the KeyError on line 307 of `kafka/producer.py`).  That code has been refactored a bit and I dont think `master` will raise a KeyError (can you test?).

That said, I dont think the current kafka-python producer code has any logic to manage metadata changes / resets -- all of that currently lives in KafkaClient.  With respect to the current master implementation, we probably need to reset `SimpleProducer.partition_cycles` and `KeyedProducer.partitioners` on errors during send_messages

**Comment by dpkp** [comment]
please reopen if KeyError is not fixed in 0.9.3 or later.  follow issue #265 for cluster metadata refresh in producers
