### ISSUE TITLE
example.py failes with No module named six

### ISSUE THREAD

**Issue by ctippur** [mumrah/kafka-python#266]
Hello,

I have followed the install instructions carefully.
when I try to run the example.py I get an error:

No module named six

I see that the module exists

$ ls -l /usr/lib/python2.6/site-packages/six.py
-rw------- 1 root root 27344 Nov 19 13:04 /usr/lib/python2.6/site-packages/six.py

Here is the trace:
$ python example.py 
Traceback (most recent call last):
  File "example.py", line 4, in <module>
    from kafka.client import KafkaClient
  File "/home/ctippur/kafka-python/kafka/__init__.py", line 9, in <module>
    from kafka.client import KafkaClient
  File "/home/ctippur/kafka-python/kafka/client.py", line 16, in <module>
    from kafka.conn import collect_hosts, KafkaConnection, DEFAULT_SOCKET_TIMEOUT_SECONDS
  File "/home/ctippur/kafka-python/kafka/conn.py", line 8, in <module>
    import six
ImportError: No module named six

**Comment by dpkp** [comment]
closing: this doesn't seem related specifically to kafka-python, and author has found a workaround

**Comment by dpriscornic** [comment]
I am sorry, I was on vacation, didn't get to test. I will test next week and get back to you. Thank you!
