### ISSUE TITLE
offset management

### ISSUE THREAD

**Issue by ctippur** [mumrah/kafka-python#267]
Hello,

Starting new here on python consumer.
I am wondering about the behaviour where if we restart the consumer, it reads the topics from the beginning. 
I see that  the offsets should be stored in zookeeper. Can you please point me to the right way to implement this so consumer read from where it left off.

- Shekar

**Comment by dpkp** [comment]
the server-side commit apis did not work until kafka 0.8.1.1 -- if you upgrade and use the `auto_commit` parameters to the consumer classes, you will get stored offsets.
