### ISSUE TITLE
how do KafkaConsumer  consume from begin or end?

### ISSUE THREAD

**Issue by scootli** [mumrah/kafka-python#293]
If I want to consumer from the begin, how to do ? In simpleConsumer, It use consumer.seek(0,0) or consumer.seek(-1,2)

**Comment by dpkp** [comment]
beginning is `seek(0,0)`

**Comment by scootli** [comment]
I am sorry, I can usderstand.  KafkaConsumer don't have seek method. The simpleConsumer have. please check. Thanks

**Comment by dpkp** [comment]
apologies -- misread it as a `SimpleConsumer` question.  For KafkaConsumer, you should use the `auto_offset_reset` config parameter, which operates the same as the java api (see http://kafka.apache.org/documentation.html#consumerconfigs "auto.offset.reset")

```
consumer = KafkaConsumer(auto_offset_reset: 'smallest')
```

alternatively, you can set offsets explicitly via `consumer.set_topic_partitions(...)`

**Comment by scootli** [comment]
Got it ,Thanks very much!

**Comment by szmcdull** [comment]
The auto_offset_reset config only applies when there is no offset set. If I've already committed an offset, how can I read again from the beginning, or from a specified offset?

**Comment by dpkp** [comment]
Try the consumer.seek* methods
