### ISSUE TITLE
Only one SimpleConsumer should read a message in a message group with several SimpleConsumers  (aka queue mode)

### ISSUE THREAD

**Issue by otso** [mumrah/kafka-python#299]
Using Kafka as a message queue, a message to a message group with several subscribing SimpleConsumers should be read by just one of them. 

So as per:

http://stackoverflow.com/questions/21809636/messages-sent-to-all-consumers-with-the-same-consumer-group-name

This seems to be still not working as per Kafka spec with the current release? Is there a proposed workaround?

Using kafka-python==0.9.2 and kafka 0.8.1.1.

**Comment by dpkp** [comment]
kafka-python does not handle this currently, though it is possible to manually manage partition assignments to your consumers (make sure that no single partition is consumed by more than one consumer instance). see #38 and #270

**Comment by mcandre** [comment]
+1 Same behavior on my machine :(

**Comment by jackyfkc** [comment]
+1
