### ISSUE TITLE
Kafka server in the NAT domain environment

### ISSUE THREAD

**Issue by chairco** [mumrah/kafka-python#300]
Hi, All 
My Kafka build in the NAT environment (2 IP in the server, ex: 169.1.1.1 is real, 10.1.1.1 is virtual)
if assign Kafka host.name = empty and advertised.host.name=10.1.1.1,I don't want Kafka server bind in the unique host. 
after try to use 169.1.1.1 to connect Kafka, but the server always return 10.1.1.1(host) then the Python-kafka will fail. look like host name bind on the 10.1.1.1

Question is can assign a host that I want use to connect Kafka not the host return by Broker metadata? if ok what should I do? 

The below information about the python-kafka process message:
DEBUG:kafka:Reinitializing socket connection for 169.1.1.1:9092
DEBUG:kafka:About to send 30 bytes to Kafka, request 0
DEBUG:kafka:Reading response 0 from Kafka
DEBUG:kafka:About to read 4 bytes from Kafka
DEBUG:kafka:Read 4/4 bytes from Kafka
DEBUG:kafka:About to read 412 bytes from Kafka
DEBUG:kafka:Read 412/412 bytes from Kafka
DEBUG:kafka:Broker metadata: [BrokerMetadata(nodeId=1, host='pshae02-pdca', port=9092), BrokerMetadata(nodeId=0, host='pshae01-pdca', port=9092)]

ex:pshae01-pdca = 10.1.1.1 (mapping by /etc/hosts)

Thanks

**Comment by chairco** [comment]
question

**Comment by dpkp** [comment]
i dont think this will work.  clients must connect to the host/ports returned in BrokerMetadata in order to follow the kafka protocol.  But your problem is really a server configuration issue, so you might try the kafka-users mailing list for better advice: `users@kafka.apache.org`

**Comment by chairco** [comment]
hi Dana,
Thanks
