### ISSUE TITLE
Raising a FailedPayloadsError loses response information for other payloads

### ISSUE THREAD

**Issue by jobevers** [mumrah/kafka-python#301]
In `client._send_broker_aware_request` (https://github.com/mumrah/kafka-python/blob/master/kafka/client.py#L199), if failed_payloads exists, raising an Exception will cause the lose of the other response information (in `acc`)

Is there a reason for raising the Exception?  Would it be acceptable to return that information along with the responses instead?

**Comment by dpkp** [comment]
agree -- the current error processing dates back to sept/oct 2013 and could use some love.  have time to submit a PR?

**Comment by jobevers** [comment]
It would be a backwards compatible change - I can try to take a stab at a PR if you're okay with that.

**Comment by dpkp** [comment]
please do - thanks!

**Comment by dpkp** [comment]
see #366 -- FailedPayloads() objects are now returned in the list of responses rather than raised immediately.
