### ISSUE TITLE
KeyedProducer doesn't recover from a kafka node going down

### ISSUE THREAD

**Issue by carlosperello** [mumrah/kafka-python#313]
Hi,

We are using kafka-python 0.9.3 with Kafka 0.8.2 on a cluster of three nodes. We found that if we turn down one of the kafka nodes, our producers fail to send messages to kafka until we restart them. It seems to be that kafka-python doesn't detect partition leader changes. Is that expected? may it be something we do wrong while using your library?

Thanks.

**Comment by carlosperello** [comment]
This is the error we get on the producer:

Traceback (most recent call last):
    File \"/var/www/honshuu-alerts-processing/src/serverdensity/alerts_processing/tornado/app.py\", line 102, in post
    json.dumps(payload))\n  File \"/var/www/honshuu-alerts-processing/eggs/kafka_python-0.9.3-py2.7.egg/kafka/producer/keyed.py\", line 60, in send_messages
    partition = self._next_partition(topic, key)\n  File \"/var/www/honshuu-alerts-processing/eggs/kafka_python-0.9.3-py2.7.egg/kafka/producer/keyed.py\", line 57, in _next_partition
    return partitioner.partition(key, self.client.get_partition_ids_for_topic(topic))
  File \"/var/www/honshuu-alerts-processing/eggs/kafka_python-0.9.3-py2.7.egg/kafka/partitioner/hashed.py\", line 9, in partition
    size = len(partitions)
TypeError: object of type 'NoneType' has no len()

**Comment by dpkp** [comment]
thanks for the bug report -- i wrote a quick test to verify and will see if I can fixup quickly.

**Comment by carlosperello** [comment]
I just tested your patch and it solved the issue I had. Thanks!
