### ISSUE TITLE
0.9.3 - Consumer offsets

### ISSUE THREAD

**Issue by Dinoshauer** [mumrah/kafka-python#346]
Hey, I just need to get something clarified.

Consumer offsets are still stored in ZK under  `/consumers/{group_id}/offsets/{topic_name}/{partition}`, right? I'm getting some weird results with some "long running" topics that has been deleted before, but I'm guessing it's Kafka's responsibility to reset the offset of a consumer once a topic is deleted, or?

**Comment by dpkp** [comment]
Yes -- the kafka server manages offsets storage and the paths in zookeeper.  There is now server support for storing offsets in a kafka topic instead of zookeeper, but kafka-python does not have support for that yet.

**Comment by Dinoshauer** [comment]
Thank you :)
