### ISSUE TITLE
Topics are not deleted but lingered.

### ISSUE THREAD

**Issue by HyukjinKwon** [mumrah/kafka-python#363]
When I delete a topic by `$KAFKA_HOME/bin/kafka-run-class.sh kafka.admin.DeleteTopicCommand --zookeeper localhost:2181 --topic test`, it looks the client still thinks there is the topic.

Moreover, it looks it does not create a topic as it writes a message after deleting the topic. In this case, I can send messages and get them but when I execute  `$KAFKA_HOME/bin/kafka-topics.sh --list  --zookeeper localhost:2181` to check the deleted topic (and supposed to be created), it does not show up.

Here are the input and output.

- Fisrt I added a document

```python
from kafka.client import KafkaClient
from kafka.producer import SimpleProducer
from kafka.common import LeaderNotAvailableError

client = KafkaClient("localhost:9092")
producer = SimpleProducer(client)
try:
    producer.send_messages('test', '123')
except LeaderNotAvailableError, e:
    producer.send_messages('test', '123')
```

- After checking the topic

```python
print client.topic_partitions

{'test': {0: PartitionMetadata(topic='queue-test', partition=0, leader=0, replicas=(0,), isr=(0,), error=0), 1: PartitionMetadata(topic='queue-test', partition=1, leader=0, replicas=(0,), isr=(0,), error=0)}}
```

and

```shell
$ cd $KAFKA_HOME
$ ./bin/kafka-topics.sh --list  --zookeeper localhost:2181
test
```

- I deleted the topic

```shell
$ cd $KAFKA_HOME
$./bin/kafka-run-class.sh kafka.admin.DeleteTopicCommand --zookeeper localhost:2181 --topic test
deletion succeeded!
```

- Then, I listed again to check the topic is deleted here. it shows okay when I executes the script to list topics.

```shell
$ cd $KAFKA_HOME
$ ./bin/kafka-topics.sh --list  --zookeeper localhost:2181
```

but it looks the topic still lingers in kafka-python

```python
print client.topic_partitions

{'test': {0: PartitionMetadata(topic='queue-test', partition=0, leader=0, replicas=(0,), isr=(0,), error=0), 1: PartitionMetadata(topic='queue-test', partition=1, leader=0, replicas=(0,), isr=(0,), error=0)}}
```

After reloading again it's the same

```python
client.load_metadata_for_topics()
print client.topic_partitions

{'test': {0: PartitionMetadata(topic='queue-test', partition=0, leader=0, replicas=(0,), isr=(0,), error=0), 1: PartitionMetadata(topic='queue-test', partition=1, leader=0, replicas=(0,), isr=(0,), error=0)}}
```

or after creating a client again.

```python
client = KafkaClient("localhost:9092")

print client.topic_partitions

{'test': {0: PartitionMetadata(topic='queue-test', partition=0, leader=0, replicas=(0,), isr=(0,), error=0), 1: PartitionMetadata(topic='queue-test', partition=1, leader=0, replicas=(0,), isr=(0,), error=0)}}
```

Thing is, I can still produce messages to the topic. I think there should be a proper way to delete a topic in this library or at least, it has to not show deleted topics.

My kafka version is 0.8.1.1 and this library version is 0.9.3

**Comment by dpkp** [comment]
this is a server bug -- deleting topics doesn't work correctly on server 0.8.1.1.  see https://issues.apache.org/jira/browse/KAFKA-1397

**Comment by HyukjinKwon** [comment]
Oh thanks for the link. But is there any way to delete a topic in this library not the shell script?

**Comment by dpkp** [comment]
as far as I know the kafka server doesn't provide any APIs for managing topics / partitions directly. For that you have to use the command-line server tools. I believe there is some work to add APIs so client libraries could do admin tasks. If/when that gets released we'll try to add support!

**Comment by HyukjinKwon** [comment]
I have checked this with Kafka 0.8.2 and it looks all work fine :+1: 
But it dose only when I create a client instance again.

You might have to take this into account so that a client instance should not have to be re-created to get a right list of topics. :)

**Comment by dpkp** [comment]
to avoid restarting your client instance, you can use `client.reset_topic_metadata(topic)` to drop a topic from the local metadata cache. you can also use `client.reset_all_metadata()` to flush all locally-cached metadata. `load_metadata_for_topics()` currently will not delete old metadata. I'll see if that can be improved.

**Comment by HyukjinKwon** [comment]
I see. Thank you very much!
