### ISSUE TITLE
Inaccurate PartitionMetadata for ISRs

### ISSUE THREAD

**Issue by jlintz** [mumrah/kafka-python#368]
Looking at the partition metadata for my topics using the library (`client.topic_partitions['topic_name']`) I see some partitions have a lower ISR count than the replicas.  Looking at zookeeper though shows all the replicas being in-sync.  I'm not quite sure why its reporting a few partitions as being out of sync.  I've tried the `load_metadata_for_topics` method to refresh the data but it's still showing some partitions with missing ISRs.  It appears to be the same partitions and brokers each time, the number doesn't seem to vary and it's not for all partitions for each of the brokers either.

This is on Kafka 0.8.1 and using 0.9.3 version of this module.

**Comment by dpkp** [comment]
I believe this is a server bug fixed in 0.8.2 . kafka-python does not connect directly to zookeeper, instead we use the Kafka APIs to query broker metadata (see https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-MetadataResponse).

**Comment by jlintz** [comment]
hm, seems like they are voting to possibly remove ISR from metadata response in future https://issues.apache.org/jira/browse/KAFKA-1367

**Comment by dpkp** [comment]
I believe this is resolved as a server-issue. Please reopen if not!
