### ISSUE TITLE
Performing a seek with the Multiprocess Consumer

### ISSUE THREAD

**Issue by alisaifee** [mumrah/kafka-python#372]
In some cases I need to fast forward my consumer to the latest available message offset but I can't find a way to do this with the Multiprocess consumer.

**Comment by dpkp** [comment]
there isn't a good interface for this right now w/ multiprocess consumer. there was a discussion about this on IRC a while back: https://botbot.me/freenode/kafka-python/2014-11-10/?msg=25204023&page=1

I think the way folks have handled this in the past is either to transition off of MultiProcessConsumer (it isn't well supported), or to set the offsets manually via a SimpleConsumer and commit those offsets before restarting the multiprocess consumer.

**Comment by alisaifee** [comment]
Yeah that's what I ended up doing as well as I couldn't think of an appropriate consistent seek interface that works post startup.
