### ISSUE TITLE
kafka.common.ConsumerFetchSizeTooSmall when processing large messages

### ISSUE THREAD

**Issue by hellais** [mumrah/kafka-python#377]
I am processing a quite large message (adding some hackish debug lines I see the message size is 1048576 bytes).

I have increased the kafka maximum byte size to 10MB so it should not be an issue with the broker, however kafka-python crashes with the following undescriptive error:

```
Traceback (most recent call last):
  File "kafka-consume.py", line 176, in <module>
    bucket_timeout)
  File "kafka-consume.py", line 149, in consume_messages
    for message in consumer:
  File "/home/ooni/.virtualenvs/pipeline/lib/python2.7/site-packages/kafka/consumer/kafka.py", line 339, in next
    return six.next(self._get_message_iterator())
  File "/home/ooni/.virtualenvs/pipeline/lib/python2.7/site-packages/kafka/consumer/kafka.py", line 423, in fetch_messages
    for (offset, message) in resp.messages:
  File "/home/ooni/.virtualenvs/pipeline/lib/python2.7/site-packages/kafka/protocol.py", line 143, in _decode_message_set_iter
    raise ConsumerFetchSizeTooSmall()
kafka.common.ConsumerFetchSizeTooSmall
```

I noticed somebody was experiencing a similar problem in the past (https://github.com/mumrah/kafka-python/issues/41), but that ticket claims it was fixed.

Any idea what may be causing this or how to debug it?

Thanks!

**Comment by dpkp** [comment]
This error typically means that your consumer's `fetch_message_max_bytes` setting is too low. Try something like:
```
kafka = KafkaConsumer('topic_foo', fetch_message_max_bytes=(1024*1024))
```

If that does not work, can you paste the code you are using to initialize KafkaConsumer ?

**Comment by dpkp** [comment]
Please re-open if the suggestion above did not fix your issue!

**Comment by hellais** [comment]
@dpkp I can confirm that your suggested fix does indeed resolve my issue. It may be worthwhile, though, to perhaps make the error message a bit more descriptive.
