### ISSUE TITLE
How to seek in KafkaConsumer 

### ISSUE THREAD

**Issue by jameswnl** [mumrah/kafka-python#382]
Hi,

I need to consumer from the earliest possible offset of certain partition.  I am using KafkaConsumer and I don't see there's something like SimpleConsumer.seek().

I also can use KafkaConsumer.set_topic_partitions().  However, I'll need to find out the earliest offset of that partition first and from my (limited) digging, I can't find it.  I tried always set to offset=0, but that would fail and started from latest offset.

Any pointer will be appreciated.

thanks,
James

**Comment by dpkp** [comment]
You should be able to configure your KafkaConsumer with `auto_offset_reset='smallest'`

see: 
http://kafka-python.readthedocs.org/en/latest/apidoc/kafka.consumer.html#module-kafka.consumer.kafka

**Comment by jameswnl** [comment]
@dpkp Thanks Dana. That seems would do.  I'll give it a try.

**Comment by jameswnl** [comment]
Yep, this parameter works.
Closing issue.
