### ISSUE TITLE
NameError: global name 'kafka' is not defined in KafkaConsumer example

### ISSUE THREAD

**Issue by abc12312** [mumrah/kafka-python#390]
Hello,

I get an error: "global name 'kafka' is not defined", when I am trying to run KafkaConsumer as it is discribed in official "usage" page: 
1. https://github.com/mumrah/kafka-python/blob/master/docs/usage.rst
2. http://kafka-python.readthedocs.org/en/latest/usage.html#kafkaconsumer
The only change was that I have tried to use kafka.close() in exit from infinit loop ("for message in consumer") under specific condition.

In this context, I have several questions:
1. I suppose there is mistyping in this example and kafka,close() will work for other examples ("SimpleProducer", "Low level", "Multiprocess consumer") who uses "KafkaClient" am I right?
2. Should one think at all about consumer stopping or closing in the case when one needs to not receive data from kafka anymore?
3. If yes, what should be instead of kafka.close() in "KafkaConsumer" example?

**Comment by dpkp** [comment]
Docs are updated to remove inadvertent reference to `kafka.close()` . You do not need to do any close() operation with KafkaConsumer. It uses generator functions instead of threading, so there is nothing that needs to be explicitly stopped.
