### ISSUE TITLE
MultiProcessConsumer run slower than single consumer

### ISSUE THREAD

**Issue by zhjchen** [mumrah/kafka-python#391]
tried to use MultiProcessConsumer, However, it runs even much slower than single KafkaConsumer. 
checked the self.queue, It is filled fast and it is always full, I think the multiprocess works.
However, the master process consumes the queue slowly. I tested two cases. 

The first one is how I use multiprocessing, I changed the queue get method in multiprocessing.py

        partition, message = self.queue.get_nowait()  ## multiprocessing.py __iter__()

        consumer = MultiProcessConsumer(client, "mygroup", "mytopics", auto_commit=True, num_procs=4)
        count = 1
        total = dict()
        while True:
                actions = list()
                try:
                        for m in consumer:
                                try:
                                        count+=1
                                        print count
                                except ValueError:
                                        continue
                except ConsumerTimeout:
                        print datetime.datetime.now()
                        print "consumer timeout"

In comparison, the following is single process case, 

        consumer = KafkaConsumer("mytopics", client_id="my-client-id", group_id="mygroup", bootstrap_servers=["xxxx:9092", "xxxx:9092" ], auto_commit_enable=True, auto_commit_interval_messages=100, auto_commit_interval_ms=2000, auto_offset_reset='largest', consumer_timeout_ms=5000)

        count = 1
        total = dict()
        while True:
                actions = list()
                try:
                        for m in consumer:
                                try:
                                        count+=1
                                        print count
                                except ValueError:
                                        continue
                except ConsumerTimeout:
                        print datetime.datetime.now()
                        print "consumer timeout"

tested the above two cases, the multiprocessing run much slower...

**Comment by dpkp** [comment]
Generally MultiProcessConsumer is slow and unmaintained. @wizzat has suggested we remove it entirely. I do not use it personally so cannot say much about its performance.

Generally, however, you would only ever want to use it if you have a particularly CPU-intensive operation to execute on each message. Python multiprocessing will add overhead that is not useful unless you plan on using multiple cpu cores.

I dont have current plans to improve MultiProcessConsumer. If you want to take a stab at improving, PRs are welcome!

**Comment by zhjchen** [comment]
Thanks, I am using multiple simple consumer, each one consumes some partitions to avoid this issue.
