### ISSUE TITLE
Add retry support for producer

### ISSUE THREAD

**Issue by mahendra** [mumrah/kafka-python#40]
I feel, we must add some retry support for producer.

If <tt>client.send_produce_request()</tt> fails, because a broker (for a partition) goes down, we can simply do 
* <tt>conn.close()</tt> and
* <tt>client.conns.pop(broker)</tt>
* try sending the message again, possibly after a retry delay.

This will ensure that the new broker for a partition will come up and we can send the message again.

This can be done after #33 is merged.

**Comment by dpkp** [comment]
#331 and related prs are merged -- async producer should handle retries properly now.
