### ISSUE TITLE
Staled topic metadata

### ISSUE THREAD

**Issue by chenziliang** [mumrah/kafka-python#400]
Hi,

I am using the current Kafka Python Client. I encountered the stale meta data for topics. What I am trying to do is monitoring the (new) topics by monitoring the /brokers/topics zookeeper node by using zookeeper python client. When there is a change notification, I did a kafka_client.reset_all_metadata() and then followed by a call of kafka_client.load_metadata_for_topics(), but seems that kafka_client.load_metadata_for_topics() can't not discover the new created topics. kafka-topics.sh --list can list the newly created topics. And if i wait for a moment, kafka_client.load_metadata_for_topics() can discover the new topics.

My expectaion is kafka_client.load_metadata_for_topics() will do a refresh by querying the broker lively.

Thanks !

**Comment by dpkp** [comment]
KafkaClient.load_metadata_for_topics() will always fetch the latest metadata from the kafka brokers (you dont need to call reset_all_metadata() beforehand, though it doesn't hurt). The response you get via kafka-python is what is reported by the kafka servers.

I believe what you are seeing is the kafka server's MetadataCache (see https://github.com/apache/kafka/blob/0.8.2/core/src/main/scala/kafka/server/MetadataCache.scala). Each kafka broker maintains an internal cache and uses that to respond to API requests. The kafka-topics.sh command you are using effectively queries zookeeper directly, which is not what the Kafka brokers do.

kafka-python does not query zookeeper directly, so you should expect to see only what the response given by the kafka broker API.

**Comment by chenziliang** [comment]
Thanks LOT for your quick response. May I ask if there is API to invalidate the cache, or I need to do periodic polling ?

**Comment by dpkp** [comment]
I don't believe there is, but you might check w/ the server mailing list users@kafka.apache.org
