### ISSUE TITLE
SimpleConsumer cannot seek to an absolute offset.

### ISSUE THREAD

**Issue by haosdent** [mumrah/kafka-python#410]
Hello, currently kafka-python only provide a relative seek method. For example, when I call `consumer.seek(offset, 0)`. The offset for current consumer would became to current_oldest_offset + `offset`, not become to 0 + `offset`. How could I seek to a fix offset in kafka-python?

**Comment by dpkp** [comment]
You might try the newer consumer class, `KafkaConsumer`. It can be configured / initialized to start at an absolute offset.  See http://kafka-python.readthedocs.org/en/latest/apidoc/kafka.html#kafka.KafkaConsumer.set_topic_partitions.

For SimpleConsumer, you have to modify internal data (can't guarantee this won't break in future releases):
```
consumer.fetch_offsets[partition] = offset
```

but it should work for now

**Comment by haosdent** [comment]
How about let me add a seek_to_absolute_offset() method to simple.py and send you a merge request?

**Comment by dpkp** [comment]
If you have time for a PR, I would prefer to keep the logic w/in the existing `seek()` function. Perhaps change the signature to:

`def seek(self, offset, whence=None, partition=None):`
and treat offset as absolute if whence is None, applying to partition (which I think would need to be required if whence is None -- i dont think it makes much sense to use a single offset applied to all partitions.)

**Comment by haosdent** [comment]
Thx, let me write.

**Comment by haosdent** [comment]
The pull request: https://github.com/mumrah/kafka-python/pull/412. Let me see the travis result first.
