### ISSUE TITLE
How to create a new topic by kafka-python?

### ISSUE THREAD

**Issue by breezedeus** [mumrah/kafka-python#438]

**Comment by peichengcheng001** [comment]
At least, there are two methods. (1) at server side, use "kafka-topics.sh". For example, Run bin/kafka-topics.sh --create --zookeeper localhost:2181 --replication-factor 1 --partitions 1 --topic test. See here, http://kafka.apache.org/documentation.html#introduction.  (2) At client side, it depends on which client lib you would like to use. In kafka-python, ensure_topic_exists() can help you. Also, see my issue here:https://github.com/mumrah/kafka-python/issues/442

**Comment by breezedeus** [comment]
Got it. Thanks much.

**Comment by jackyfkc** [comment]
`ensure_topic_exists()` only work when you configure your brokers to auto-create topics by setting `auto.create.topics.enable` to True [ The default value is True]

**Comment by paetling** [comment]
I just ran into the issue where `ensure_topic_exists()` does not create a topic for you when auto-create is off.  This is a bug.  Ensure implies that at the end of this function running my topic will be created. What is actually happening right now is an error is occurring:

```
In [9]: kafka.ensure_topic_exists('LoggedInEvent')
2015-08-06 17:44:29,468 [DEBUG]: Request 7: ['LoggedInEvent']
2015-08-06 17:44:29,469 [DEBUG]: About to send 45 bytes to Kafka, request 7
2015-08-06 17:44:29,470 [DEBUG]: Reading response 7 from Kafka
2015-08-06 17:44:29,470 [DEBUG]: About to read 4 bytes from Kafka
2015-08-06 17:44:29,471 [DEBUG]: Read 4/4 bytes from Kafka
2015-08-06 17:44:29,471 [DEBUG]: About to read 33 bytes from Kafka
2015-08-06 17:44:29,471 [DEBUG]: Read 33/33 bytes from Kafka
2015-08-06 17:44:29,472 [DEBUG]: Response 7: MetadataResponse(brokers=[], topics=[TopicMetadata(topic='LoggedInEvent', error=3, partitions=[])])
2015-08-06 17:44:29,472 [INFO]: Updating broker metadata: []
2015-08-06 17:44:29,472 [INFO]: Updating topic metadata: [TopicMetadata(topic='LoggedInEvent', error=3, partitions=[])]
---------------------------------------------------------------------------
UnknownTopicOrPartitionError              Traceback (most recent call last)
<ipython-input-9-e77aed4285e7> in <module>()
----> 1 kafka.ensure_topic_exists('LoggedInEvent')

/usr/local/lib/python2.7/dist-packages/kafka/client.pyc in ensure_topic_exists(self, topic, timeout)
    318                 raise KafkaTimeoutError('Unable to create topic {0}'.format(topic))
    319             try:
--> 320                 self.load_metadata_for_topics(topic)
    321             except LeaderNotAvailableError:
    322                 pass

/usr/local/lib/python2.7/dist-packages/kafka/client.pyc in load_metadata_for_topics(self, *topics)
    376             # Errors expected for new topics
    377             try:
--> 378                 kafka.common.check_error(topic_metadata)
    379             except (UnknownTopicOrPartitionError, LeaderNotAvailableError) as e:
    380 

/usr/local/lib/python2.7/dist-packages/kafka/common.pyc in check_error(response)
    231     if response.error:
    232         error_class = kafka_errors.get(response.error, UnknownError)
--> 233         raise error_class(response)
    234 
    235 

UnknownTopicOrPartitionError: TopicMetadata(topic='LoggedInEvent', error=3, partitions=[])
```

**Comment by rquinlivan** [comment]
@paetling Auto topic creation must be enabled in your server.properties.

**Comment by paetling** [comment]
Ok, but just sending data to kafka automatically creates topics when that property is enabled.  Seems like this function is not really giving a ton of value if it does not actually create topics for me when this property is off.   
If this is the desired behavior and you do not plan on changing it any time soon (or it is impossible to create topics through python when this property is off), I think the docs should be updated to reflect this information.

**Comment by rquinlivan** [comment]
@paetling I'm not an author of this library, I'm only echoing what I know of the Kafka project. Manual programmatic topic creation is not exposed in the API, as far as I know. Topics must either be auto-created or else created using the shell tools in /opt/kafka/bin. I agree, then, that `ensure_topic_exists` should have its documentation updated accordingly.

**Comment by paetling** [comment]
@rquinlivan   In that case, i really appreciate the help :)

**Comment by dpkp** [comment]
@paetiling As far as I know, it is currently impossible to create topics explicitly using the public kafka API, so there is no way to support topic creation via kafka-python if `auto.create.topics.enable` is false.

**Comment by rinatio** [comment]
@dpkp There seems to be some updates in API — http://stackoverflow.com/a/23360100/1224211

**Comment by dpkp** [comment]
No, those are all references to the Java class interfaces. See KIP-4
discussion re API development.

**Comment by chiwah-keen** [comment]
set auto.create.topics.enable  is true, is also not work. when produce message to a noexist topic
