### ISSUE TITLE
Messages being broadcast to consumers in same group

### ISSUE THREAD

**Issue by nursejason** [mumrah/kafka-python#444]
I have two consumers in the same group and both are receiving each message that I push up into the queue. I am consuming the message on consumer 1 and committing the consumption to Kafka, then checking pending messages and verifying that it is at 0. Consumer 2 is constantly checking pending messages, and never goes down after a message has been pushed, despite appropriate message consumption from consumer 1.     
      
Restarting consumer 2 resets pending message counter back to 0, which validates that the commit logic is working appropriately. 

Kafka v 0.8.1.1
kafka-python release 0.9.x

**Comment by bgdnlp** [comment]
Can confirm, I'm seeing the same thing on the same server version. Auto-commiting or commiting each message after print(), makes no difference. Both consumers get all messages.

**Comment by dpkp** [comment]
This is expected -- consumer coordination is not natively supported by kafka-python. See #455 and #38 .
