### ISSUE TITLE
Consumer group not working with 0.9.4 and broker 0.8.2.1

### ISSUE THREAD

**Issue by szelok** [mumrah/kafka-python#455]
I tried both SimpleConsumer and KafkaConsumer - setup two consumers in group and subscribe to same topic. Both consumers got same messages. I was expecting load balancing. But it is not happening. Pls advise. Thanks,

**Comment by Ormod** [comment]
Did you have more than one partition set per topic?

**Comment by dpkp** [comment]
kafka-python does not support consumer coordination automatically. See Issue #38 . Kafka requires that this be managed client side, including (presumably) leveraging a distributed state management store like Zookeeper, consul, or etcd. I expect that kafka-python will not support this unless / until the functionality is moved to the server (perhaps in v0.9 of apache kafka)

**Comment by dpkp** [comment]
Further comment: you can manage this explicitly by assigning each of your consumers to different partitions on the same topic. The kafka-python consumer apis should make this possible w/ the current release. But you will not get auto-assignment, failover, load balancing, etc.

**Comment by szelok** [comment]
cool. thanks

**Comment by CVTJNII** [comment]
I'm confused, per the Kafka docs:

> Consumers label themselves with a consumer group name, and each message published to a topic is delivered to one consumer instance within each subscribing consumer group. Consumer instances can be in separate processes or on separate machines.
> - http://kafka.apache.org/08/introduction.html

So with the same group ID I expect messages to balance between consumers.  However, I'm not seeing this with multiple processes running kafka.SimpleConsumer() with the group argument set identically.  Can you elaborate on 'Kafka requires that this be managed client side' more?  Per the Kafka docs I expect this not to be the case with the same consumer group_id.

**Comment by dpkp** [comment]
The official kafka docs are biased towards the java client. Until 0.9.0.0, the "balancing" functionality was managed externally to the kafka system -- java clients connect directly to zookeeper and implement their own leadership, election, and balancing algorithm.

Starting in kafka 0.9.0.0, the kafka server added APIs to manage balancing. kafka-python will support those, but you'll need to use the newer kafka broker (>- 0.9.0.0). (see the `0.9` branch for the latest code).

**Comment by CVTJNII** [comment]
@dpkp Would that be the kafka.KafkaConsumer() consumer in the latest docs, then?

**Comment by CVTJNII** [comment]
Aah, never mind.  I think I see my answer down at the bottom of #38.
