### ISSUE TITLE
KafkaException if offset value is more than available offsets.

### ISSUE THREAD

**Issue by xrage** [mumrah/kafka-python#97]
req = FetchRequest(topic='test', partition=0, offset=100, max_bytes=1000000)
here last offset value is 39 in my case so 

kafka.send_fetch_request([req])

throwing an exception 
Exception message is - 
    FetchRequest for TopicAndPartition(topic='test', partition=0) failed with errorcode=1

It will be good if we have a KafkaException defined like version 0.7.

**Comment by dpkp** [comment]
#158 fixed.
